accounts/urls.py
from django.urls import path,re_path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

articles/urls.py
from django.urls import path,re_path
from . import views


app_name = 'articles'

urlpatterns = [
    path('',views.article_list,name="list"),
    path('create',views.article_create,name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$',views.article_details,name="detail"),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),
    path('about/',views.about),
    path('',article_views.article_list,name="home"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import DO_NOTHING


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug  = models.SlugField()
    body  = models.TextField()
    date  = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg',blank=True)
    author = models.ForeignKey(User,default=None,on_delete=DO_NOTHING)
    


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '......'

articles/forms.py
from django import forms 
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.http import request
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log user in
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
       form = AuthenticationForm(data=request.POST)
       if form.is_valid():
           #log in user
           user = form.get_user()
           login(request,user)
           if 'next' in request.POST:
               return redirect(request.POST.get('next'))
           else:
                return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import redirect, render
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})


def article_details(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_details.html',{'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            #save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form': form})

blogapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('homepage')
    return render(request,'homepage.html')


def about(request):
    #return HttpResponse('about')
    return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<link rel="stylesheet" href="{% static 'login.css' %}">
<div class="row justify-content-center" id="title">
   <h2>LOGIN AND CREATE BLOGS!</h2>
</div>
<div class="container mt-5 d-flex justify-content-center" id="login">
   <div class="col-sm-6 mt-5">
      <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
         {% csrf_token %}
         {{form|crispy}}
         {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next}}">
          {% endif %}
          
         <input type="submit" class="btn btn-primary btn-large mt-5 mb-5" name="" value="login" style="margin-left: 45%;">
      </form>
   </div>
</div>
 
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}


{% block content %}
   <h1>sign up page</h1>
   <form class="site-form" action="/accounts/signup/" method="POST">
      {% csrf_token %}
      {{form}}
      <input type="submit" name="" value="signup">
   </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<link rel="stylesheet" href="{% static 'article_create.css' %}">
    <div class="row  d-flex justify-content-center" id="title">
        <p><h2>CREATE AN AMAZING BLOG!</h2></p>
    </div>
    <div class="container mt-5 d-flex justify-content-center" id="create">
        <div class="col-sm-6 mt-4 justify-content-center">
            <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary btn-large mt-5 mb-5" value="CREATE" style="margin-left: 45%;">
            </form>
        </div>
    </div>
{% endblock %}

articles/templates/articles/article_details.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'article_detail.css' %}">
<div class="row d-flex justify-content-center mt-4 ">
    <h2><strong>{{article.title}}</strong></h2>
</div>
<div class="container mt-5">
    <div class="card-deck">
        <div class="card">
          <img class="card-img-top" src="{{article.thumb.url}}" alt="Card image cap " style="width: 1107px; height: 600px;">
          <div class="card-body">
            <h5 class="card-title"><em>{{article.title}}</em></h5>
            <p class="card-text">{{article.body}}</p>
            <p class="card-text"><small class="text-muted">{{article.date}}</small></p>
          </div>
        </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content%}
<link rel="stylesheet" href="{% static 'article_list.css' %}">
<div class="row justify-content-center mt-5 mb-5">
    <h3><i class="fas fa-hamburger"></i>The Personal Blog</h3>
</div>
<div class="container mt-3 justify-content-center " style="display:flex; flex-wrap: wrap;">

{% for article in articles %}
    
        <div class="col-sm-6 col-md-3 mt-4 mr-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{article.thumb.url}}" alt="Card image cap" style=" height:150px">
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h5>
                  <p class="card-text">{{article.snippet}}</p>
                  <p class="card-text"><small class="text-muted">{{article.date}}</small></p>
                 
                </div>
              </div>
        </div>
    
        
        
{% endfor %}
</div>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ABOUT</title>
</head>
<body>
    <h1>know about us</h1>
</body>
</html>

templates/base_layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'nav.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Welcome to my blog</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg ">
      <a class="navbar-brand" href="#"><i class="fas fa-hamburger"></i>The Personal Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      {% if user.is_authenticated %}
       <div class="navbar-nav ml-auto">
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-outline-light" type="submit">Logout</button>
        </form>
        </div>
        <a class="nav-item nav-link" href="{% url 'articles:create' %}">Create a New Article</a>
        {%else%}
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          </div>
        {% endif %} 
        </div>
    </nav>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>Welcome to the Homepage</h1>
</body>
</html>